### ISSUE TITLE
[RFC] Poet - avoid late challenge registration

### ISSUE THREAD

**Issue by poszu** [spacemeshos/pm#205]
### Motivation
When a node builds an ATX it must commit the nipost challenge to a specific epoch (specified by `PubLayer ID`). The ATX will then be valid (and give eligibility) only in that epoch. It is thus essential that the ATX is built and published before the epoch it targets and on time to use it as part of the challenge to build the next ATX (ATXes are chained via the `Previous ATX` field).

#### Let's consider an example below.
A node wants to build an ATX for round `N`. It should submit a challenge to a Poet service in round `N-2` so that it gets the poet proof in the epoch `N-1`. 
However, it is possible that a node submits the challenge too late, missing the open registration window in a round `N-2`, which finishes (and yields a PoET proof) in epoch `N-1` (green). It will instead register in round `N-1` (red). If this happens, the node will receive its PoET proof already in epoch `N` and its ATX will only be useful for the remaining part of epoch `N`. 

:bulb: If a node misses registration in one node (or a few, but not **all**), it wouldn't wait that long and would use proof from another poet.

:bulb: This situation might happen because of timing issues or if a node was off (smapp closed etc.) for some period of time. It has already happened in https://github.com/spacemeshos/go-spacemesh/issues/3917.

![image](https://user-images.githubusercontent.com/3966964/210221416-24426e5b-80dc-4925-aba3-d942b462cb5e.png)

### Problem statement
Given the changes introduced in https://github.com/spacemeshos/go-spacemesh/issues/3458, a node can only submit one challenge for a given round. Thus, the missed registration in round `N-1` (red) prevents the node from re-registering with an updated nipost challenge targeting epoch `N+1` in this Poet service.

### Proposed mitigation
@noamnelke proposed mitigation. Copying over from Slack channel:
>When the node submits a challenge to the PoET it should include its deadline for the proof. If the PoET sees that the node’s deadline is before its own deadline - it rejects the registration (and returns an error that the node can log). This tells the node ahead of time that the registration failed, allows us to see this in the logs, prevents blocking registration for the next round and also prevents unneeded/unused registrations in the PoET membership tree.
>
>The node already knows its deadline, so it shouldn’t be hard to include this information in the PoET registration. The PoET also knows its round end time, so it shouldn’t be hard to check this when a node registers.

### Additional thoughts
On the other hand, the late ATX (in the example above), is still valid for a majority of epoch `N`. Completely rejecting the late registration will result in a node not having an ATX for a whole epoch. (The current implementation wouldn't wait for it, however, as the nipost builder is forced to finish before the ATX publication time).

**Comment by noamnelke** [comment]
> still valid for a majority of epoch `N`.

This is not always true, depending on the PoET phase (when in the epoch it starts). For some PoETs it might be the start of the epoch, and then you're right, but this is not necessarily the case. Another question is "how do you proceed from there?". For your next ATX, do you target epoch `N+1`? If so you're gonna publish the ATX late in that epoch as well, and forever, until you skip an epoch. If you're gonna skip an epoch anyway, you might as well do it immediately.

I think the behavior should be as follows:
- Try to register for PoETs using the logic I proposed (restrict completion time).
- If some registrations failed, but at least one succeeded (e.g. borderline timing) then just count on the successful registrations.
- If ALL registrations failed, then you're gonna have to skip an epoch at some point - might as well do it immediately. You can create a new challenge, skipping an epoch, and submit it to all PoETs early.

---
Otherwise description looks clear and accurate.

**Comment by poszu** [comment]
Closing as implemented already
